amazon_s3_access_key_id: 2XVW5WUHI3KAX5FCOA5K
amazon_s3_access_key_secret: kgjJY0xpmtG7jelBTAuiFebXKB6tdm0k7ErYsT6R
devise_pepper: 8515ff1197799eed94dc596257f7e459e564bad2e9664d0f77755564eca0e656e5682618d5e8aadc8b8b96d53d2a97321d45e4b88237cb80ec67f820aa5e1cbe
devise_secret_key: b5befc05ddfc36049bad568d325a2b0556f92e0701218aa3d662e96ebd2db19f2c8f9e56d046c38938bf94e9a06e8cae59215d591274d3a6de5cb76ca0f4e72e
github_client_id: b657ae74187b2166988f
github_client_id_stg: 4a9dc06681e485b406de
github_client_secret: 64875198becbc7b301d308fd500ad552506d19f7
github_client_secret_stg: 3f851c5a870ede307ea48a25d94e9e5d0a9d30e4
raven_dsn: https://c2135b1d5f8fb794379ee872f12ab4ea:3d96e586a0099b6fde62460c3f72415f@sentry.io/6865229
recaptcha_secret_key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
recaptcha_secret_key_stg: 6Lc6BAAAAAAAAKN3DRm6VA_UF7hM3nvP03owVwPX4b0yYVscpt
secret_key_base: d6d481302491e4bcb317d385716d43781a676f0991e6528d1f77434122d2409e1ee4cd9d20667f2cfbdb474119a2e39df2c813e2c0a91c13d4f9bdd829dcd65b
sendgrid_api_key: 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
superuser_email: admin@example.com
superuser_password: 77a021e17525fe158dc90d093e5afd27
telegram_bot_api_token: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11
