default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('POSTGRES_PORT') { 5432 } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'partynest' } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'partynest_development' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>

test: &test
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'partynest_test' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password' } %>

cucumber:
  <<: *test

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'partynest_production' } %>
  password: <%= Rails.application.credentials.postgres_password %>
