default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('POSTGRES_POOL') { 5 } %>

unsafe: &unsafe
  <<: *default
  host:     <%= ENV.fetch('POSTGRES_HOST')     { 'localhost' } %>
  port:     <%= ENV.fetch('POSTGRES_PORT')     { 5432        } %>
  username: <%= ENV.fetch('POSTGRES_USER')     { 'partynest' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'password'  } %>

development:
  <<: *unsafe
  database: <%= ENV.fetch('POSTGRES_DB') { 'partynest_development' } %>

test: &test
  <<: *unsafe
  database: <%= ENV.fetch('POSTGRES_DB') { 'partynest_test' } %>

cucumber:
  <<: *test

production:
  <<: *default
  host: 'private-partynest-do-user-4455684-0.db.ondigitalocean.com'
  port: 25060
  database: 'partynest_production'
  username: 'doadmin'
  password: <%= Rails.application.credentials.postgres_password %>
