default:
  host:     <%= ENV.fetch('RAILS_CACHE_REDIS_HOST')     { 'localhost' } %>
  port:     <%= ENV.fetch('RAILS_CACHE_REDIS_PORT')     { 6379        } %>
  db:       <%= ENV.fetch('RAILS_CACHE_REDIS_DB')       { 1           } %>
  password: <%= ENV.fetch('RAILS_CACHE_REDIS_PASSWORD') { 'password'  } %>

production:
  host:     'private-db-redis-ams3-76837-do-user-4455684-0.db.ondigitalocean.com'
  port:     25061
  password: <%= Rails.application.credentials.sidekiq_cache_redis_password %>
  db:       1
  ssl:
    ca_file: <%= Rails.root.join 'config', 'redis.crt' %>
