default: &default
  host:     <%= ENV.fetch('SIDEKIQ_CLIENT_REDIS_HOST')     { 'localhost' } %>
  port:     <%= ENV.fetch('SIDEKIQ_CLIENT_REDIS_PORT')     { 6379        } %>
  password: <%= ENV.fetch('SIDEKIQ_CLIENT_REDIS_PASSWORD') { 'password'  } %>

development:
  <<: *default
  db: <%= ENV.fetch('SIDEKIQ_CLIENT_REDIS_DB') { 0 } %>

test:
  <<: *default
  db: <%= ENV.fetch('SIDEKIQ_CLIENT_REDIS_DB') { 15 } %>

production:
  host:     'private-db-redis-ams3-76837-do-user-4455684-0.db.ondigitalocean.com'
  port:     25061
  password: <%= Rails.application.credentials.sidekiq_client_redis_password %>
  db:       0
  ssl:      true
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
    ca_file:     <%= Rails.root.join 'config', 'certs', 'redis.crt' %>
