production:
  address: smtp.sendgrid.net
  port: 587
  domain: libertarian-party.com
  user_name: apikey
  password: <%= Rails.application.credentials.sendgrid_api_key %>
  authentication: plain
  enable_starttls_auto: true
  openssl_verify_mode: none
